dist: bionic
sudo: false
language: java

before_install:
  - git clone --depth 1 https://github.com/fastily/jwiki.git
  - pushd jwiki
  - ./gradlew publishToMavenLocal -x signMavenJavaPublication
  - popd
  - git clone --depth 1 https://github.com/fastily/wp-toolbox.git
  - pushd wp-toolbox
  - ./gradlew publishToMavenLocal
  - popd

notifications:
  email: false